// Weapon definitions - Vampire Survivors style
export const AUTO_WEAPONS = {
  // Starting weapon - simple projectile
  magicWand: {
    id: "magicWand",
    name: "Magic Wand",
    rarity: "common",
    description: "Fires at the nearest enemy",
    iconColor: "#00ccff",
    icon: `<i class="fa-solid fa-wand-magic-sparkles"></i>`,
    maxLevel: 8,
    baseStats: {
      damage: 10,
      cooldown: 0.5,
      projectileCount: 1,
      projectileSpeed: 35,
      pierce: 0,
      area: 1.0,
      duration: 1.5,
    },
    levelBonuses: [
      {},
      { damage: 3 },
      { projectileCount: 1, cooldown: -0.05 },
      { damage: 4 },
      { pierce: 1, cooldown: -0.05 },
      { damage: 5, projectileCount: 1 },
      { cooldown: -0.05 },
      { damage: 5, projectileCount: 1 },
    ],
  },

  // Whip - horizontal attack
  whip: {
    id: "whip",
    name: "Whip",
    rarity: "common",
    description: "Attacks horizontally, passes through enemies",
    iconColor: "#cc4444",
    icon: '<i class="fa-solid fa-bolt"></i>',
    maxLevel: 8,
    baseStats: {
      damage: 15,
      cooldown: 1.5,
      projectileCount: 1,
      area: 1.0,
      duration: 0.3,
      knockback: 2,
    },
    levelBonuses: [
      {},
      { damage: 5, area: 0.1 },
      { projectileCount: 1 }, // Attacks behind too
      { damage: 5, area: 0.2 },
      { damage: 10 },
      { area: 0.3, knockback: 1 },
      { damage: 10 },
      { damage: 15, projectileCount: 1, area: 0.5 },
    ],
  },

  // Knife - throws in facing direction
  knife: {
    id: "knife",
    name: "Knife",
    rarity: "common",
    description: "Throws knives in facing direction",
    iconColor: "#88aaff",
    icon: '<i class="fa-solid fa-khanda"></i>',
    maxLevel: 8,
    baseStats: {
      damage: 9,
      cooldown: 0.55,
      projectileCount: 1,
      projectileSpeed: 25,
      pierce: 0,
      area: 1.0,
      duration: 1.5,
    },
    levelBonuses: [
      {},
      { damage: 3, projectileSpeed: 3 },
      { projectileCount: 1 },
      { damage: 4 },
      { pierce: 1, projectileCount: 1 },
      { damage: 5, cooldown: -0.05 },
      { projectileCount: 1 },
      { damage: 5, projectileCount: 1 },
    ],
  },

  // Axe - thrown in arc
  axe: {
    id: "axe",
    name: "Axe",
    rarity: "uncommon",
    description: "High damage, passes through enemies",
    iconColor: "#ff4444",
    icon: '<i class="fa-solid fa-gavel"></i>',
    maxLevel: 8,
    baseStats: {
      damage: 25,
      cooldown: 1.8,
      projectileCount: 1,
      projectileSpeed: 8,
      pierce: Infinity,
      area: 1.2,
      duration: 3.0,
    },
    levelBonuses: [
      {},
      { damage: 10 },
      { projectileCount: 1 },
      { damage: 10, area: 0.2 },
      { projectileCount: 1 },
      { damage: 15 },
      { projectileCount: 1, cooldown: -0.2 },
      { damage: 20, projectileCount: 1 },
    ],
  },

  // Garlic - damage aura
  garlic: {
    id: "garlic",
    name: "Garlic",
    rarity: "uncommon",
    description: "Damages nearby enemies and knocks them back",
    iconColor: "#88cc44",
    icon: '<i class="fa-solid fa-shield-cat"></i>',
    maxLevel: 8,
    baseStats: {
      damage: 5,
      cooldown: 0.5,
      area: 2.0,
      knockback: 1.5,
      duration: 0.3,
    },
    levelBonuses: [
      {},
      { area: 0.3 },
      { damage: 2 },
      { area: 0.4, knockback: 0.5 },
      { damage: 3 },
      { area: 0.5 },
      { damage: 3, cooldown: -0.05 },
      { damage: 5, area: 1.0 },
    ],
  },

  // Cross/Boomerang - returns to player
  cross: {
    id: "cross",
    name: "Cross",
    rarity: "rare",
    description: "Boomerangs around, deals damage on the way back",
    iconColor: "#ffcc00",
    icon: '<i class="fa-solid fa-cross"></i>',
    maxLevel: 8,
    baseStats: {
      damage: 15,
      cooldown: 1.2,
      projectileCount: 1,
      projectileSpeed: 10,
      pierce: Infinity,
      area: 1.0,
      duration: 3.0,
    },
    levelBonuses: [
      {},
      { damage: 5, projectileSpeed: 2 },
      { projectileCount: 1 },
      { damage: 5, area: 0.2 },
      { projectileCount: 1 },
      { damage: 10 },
      { cooldown: -0.1 },
      { projectileCount: 1, damage: 10 },
    ],
  },

  // Fire Wand - area explosion
  fireWand: {
    id: "fireWand",
    name: "Fire Wand",
    rarity: "uncommon",
    description: "Fires explosive projectiles",
    iconColor: "#ff6600",
    icon: '<i class="fa-solid fa-fire"></i>',
    maxLevel: 8,
    baseStats: {
      damage: 20,
      cooldown: 1.5,
      projectileCount: 1,
      projectileSpeed: 12,
      area: 1.5,
      explosionRadius: 2,
      duration: 2.0,
    },
    levelBonuses: [
      {},
      { damage: 5 },
      { explosionRadius: 0.5 },
      { damage: 10, projectileCount: 1 },
      { explosionRadius: 0.5, cooldown: -0.1 },
      { damage: 10 },
      { projectileCount: 1 },
      { damage: 15, explosionRadius: 1.0 },
    ],
  },

  // Lightning Ring - random strikes
  lightning: {
    id: "lightning",
    name: "Lightning Ring",
    rarity: "rare",
    description: "Strikes random enemies in range",
    iconColor: "#ffdd00",
    icon: '<i class="fa-solid fa-bolt"></i>',
    maxLevel: 8,
    baseStats: {
      damage: 15,
      cooldown: 1.0,
      projectileCount: 1,
      area: 5.0,
      duration: 0.1,
    },
    levelBonuses: [
      {},
      { damage: 5 },
      { area: 1.0, projectileCount: 1 },
      { damage: 5 },
      { area: 1.0, projectileCount: 1 },
      { damage: 8, cooldown: -0.1 },
      { projectileCount: 1 },
      { damage: 10, projectileCount: 1 },
    ],
  },

  // Runetracer - bouncing projectile
  runetracer: {
    id: "runetracer",
    name: "Runetracer",
    rarity: "rare",
    description: "Bouncing projectile that lasts a long time",
    iconColor: "#ff44ff",
    icon: '<i class="fa-solid fa-gem"></i>',
    maxLevel: 8,
    baseStats: {
      damage: 10,
      cooldown: 3.0,
      projectileCount: 1,
      projectileSpeed: 8,
      pierce: Infinity,
      duration: 5.0,
      bounces: true,
    },
    levelBonuses: [
      {},
      { damage: 5, projectileSpeed: 1 },
      { duration: 1.0 },
      { damage: 5, projectileCount: 1 },
      { duration: 1.0 },
      { damage: 10 },
      { projectileCount: 1, cooldown: -0.3 },
      { damage: 10, duration: 2.0 },
    ],
  },

  // Holy Water - ground area damage
  holyWater: {
    id: "holyWater",
    name: "Holy Water",
    rarity: "uncommon",
    description: "Throws bottles that create damaging pools",
    iconColor: "#44aaff",
    icon: '<i class="fa-solid fa-droplet"></i>',
    maxLevel: 8,
    baseStats: {
      damage: 8,
      cooldown: 2.0,
      projectileCount: 1,
      area: 2.0,
      duration: 3.0,
      tickRate: 0.3,
    },
    levelBonuses: [
      {},
      { damage: 2, area: 0.3 },
      { projectileCount: 1 },
      { damage: 3, duration: 0.5 },
      { area: 0.4 },
      { projectileCount: 1, damage: 3 },
      { duration: 1.0, cooldown: -0.2 },
      { damage: 5, projectileCount: 1, area: 0.5 },
    ],
  },

  // === NEW WEAPONS ===

  // Bone - bounces between enemies
  bone: {
    id: "bone",
    name: "Bone",
    rarity: "common",
    description: "Bounces between enemies, hitting multiple times",
    iconColor: "#ddccaa",
    icon: '<i class="fa-solid fa-bone"></i>',
    maxLevel: 8,
    baseStats: {
      damage: 12,
      cooldown: 1.5,
      projectileCount: 1,
      projectileSpeed: 10,
      bounceCount: 3,
      area: 0.8,
      duration: 4.0,
    },
    levelBonuses: [
      {},
      { damage: 4, bounceCount: 1 },
      { projectileCount: 1 },
      { damage: 4, projectileSpeed: 2 },
      { bounceCount: 2 },
      { projectileCount: 1, damage: 4 },
      { cooldown: -0.2, bounceCount: 1 },
      { damage: 8, projectileCount: 1, bounceCount: 2 },
    ],
  },

  // Magic Missile - homing projectiles
  magicMissile: {
    id: "magicMissile",
    name: "Magic Missile",
    rarity: "common",
    description: "Slow but relentless homing missiles",
    iconColor: "#ff88ff",
    icon: '<i class="fa-solid fa-star"></i>',
    maxLevel: 8,
    baseStats: {
      damage: 15,
      cooldown: 2.8,
      projectileCount: 1,
      projectileSpeed: 6,
      pierce: 0,
      area: 1.0,
      duration: 5.0,
      homing: true,
      homingStrength: 2,
    },
    levelBonuses: [
      {},
      { damage: 5, projectileCount: 1 },
      { homingStrength: 0.5 },
      { damage: 5, projectileCount: 1 },
      { projectileSpeed: 1, cooldown: -0.3 },
      { damage: 8, projectileCount: 1 },
      { cooldown: -0.3 },
      { damage: 10, projectileCount: 1 },
    ],
  },

  // Peachone - orbiting bird
  peachone: {
    id: "peachone",
    name: "Peachone",
    rarity: "rare",
    description: "A bird that orbits around you, dealing damage",
    iconColor: "#ffaadd",
    icon: '<i class="fa-solid fa-dove"></i>',
    maxLevel: 8,
    baseStats: {
      damage: 10,
      cooldown: 0, // Always active
      projectileCount: 1,
      orbitRadius: 3,
      orbitSpeed: 2,
      area: 1.5,
    },
    levelBonuses: [
      {},
      { damage: 3, orbitRadius: 0.3 },
      { projectileCount: 1 },
      { damage: 4, orbitSpeed: 0.3 },
      { projectileCount: 1 },
      { damage: 5, area: 0.3 },
      { orbitRadius: 0.5, orbitSpeed: 0.3 },
      { damage: 8, projectileCount: 1 },
    ],
  },

  // Ebony Wings - dark orbiting bird (pairs with Peachone)
  ebonyWings: {
    id: "ebonyWings",
    name: "Ebony Wings",
    rarity: "rare",
    description: "A dark bird that orbits opposite to Peachone",
    iconColor: "#aa88ff",
    icon: '<i class="fa-solid fa-crow"></i>',
    maxLevel: 8,
    baseStats: {
      damage: 10,
      cooldown: 0,
      projectileCount: 1,
      orbitRadius: 3,
      orbitSpeed: -2, // Opposite direction
      area: 1.5,
    },
    levelBonuses: [
      {},
      { damage: 3, orbitRadius: 0.3 },
      { projectileCount: 1 },
      { damage: 4, orbitSpeed: -0.3 },
      { projectileCount: 1 },
      { damage: 5, area: 0.3 },
      { orbitRadius: 0.5 },
      { damage: 8, projectileCount: 1 },
    ],
  },

  // Pentagram - screen clear at intervals
  pentagram: {
    id: "pentagram",
    name: "Pentagram",
    rarity: "legendary",
    description: "Periodically erases all enemies on screen",
    iconColor: "#ff4444",
    icon: '<i class="fa-solid fa-star-of-david"></i>',
    maxLevel: 8,
    baseStats: {
      damage: 999,
      cooldown: 60, // Very long cooldown
      area: 50, // Full screen
      duration: 0.5,
    },
    levelBonuses: [
      {},
      { cooldown: -10 },
      { cooldown: -8 },
      { cooldown: -6 },
      { cooldown: -5 },
      { cooldown: -5 },
      { cooldown: -5 },
      { cooldown: -5 },
    ],
  },

  // Clock Lancet - freeze enemies
  clockLancet: {
    id: "clockLancet",
    name: "Clock Lancet",
    rarity: "rare",
    description: "Freezes enemies in place temporarily",
    iconColor: "#88ddff",
    icon: '<i class="fa-solid fa-clock"></i>',
    maxLevel: 8,
    baseStats: {
      damage: 1,
      cooldown: 2.0,
      area: 4.0,
      freezeDuration: 1.0,
      duration: 0.1,
    },
    levelBonuses: [
      {},
      { area: 0.5, freezeDuration: 0.2 },
      { area: 0.5 },
      { freezeDuration: 0.3 },
      { area: 1.0 },
      { freezeDuration: 0.3, cooldown: -0.2 },
      { area: 1.0 },
      { freezeDuration: 0.5, area: 2.0 },
    ],
  },

  // Laurel - temporary invincibility
  laurel: {
    id: "laurel",
    name: "Laurel",
    rarity: "rare",
    description: "Grants brief invincibility when taking fatal damage",
    iconColor: "#44cc44",
    icon: '<i class="fa-solid fa-leaf"></i>',
    maxLevel: 8,
    baseStats: {
      cooldown: 60, // Once per minute
      shieldDuration: 1.0,
    },
    levelBonuses: [
      {},
      { shieldDuration: 0.3 },
      { cooldown: -10 },
      { shieldDuration: 0.3 },
      { cooldown: -10 },
      { shieldDuration: 0.5 },
      { cooldown: -10 },
      { shieldDuration: 1.0, cooldown: -10 },
    ],
  },
};
